// updated 03/30/2026
const cardConfig = {
  title: "KJW Music",
  subtitle: "",
  note:
    "Just press play,  and let the songs do the talking.",
  sender: "",
  recipient: "",
  senderAsideHtml: "",
};


//updated 03/23/2026
//Kevin's Playlist
const songs = [
    {
    name: "Incredible Love",
    artist: "Ingrid Michaelson",
    file: "https://dl.dropboxusercontent.com/scl/fi/owd2m0xdvjw9vn3lfgd8a/05-Incredible-Love.mp3?rlkey=c3y1mmiyh1dlol6w23ylzetaz&st=09bsyaua&dl=0",
    play: true,
  },   
  {
    name: "Traveling Soldier",
    artist: "Cody Johnson",
    file: "https://dl.dropboxusercontent.com/scl/fi/rzu0tfan9pg3i9agrr194/Cody-Johnson-Travelin-Soldier-Acoustic.mp3?rlkey=dgwzbk60bwb1kuaisquma5lxb&st=it3va71d&dl=0",
    play: true,
  },
  {
    name: "Sail with Ease",
    artist: "Liam Bailey",
    file: "https://dl.dropboxusercontent.com/scl/fi/8jgfdlz04h1dx8l36yyk3/Sail-with-Ease-n5Ur0835UuU.mp3?rlkey=b977fu7ro9uyyrr3ogox825qs&st=zjjbmiai&dl=0",
    play: true,
  },
  {
    name: "Rock and a Hard Place",
    artist: "Bailer Zimmerman",
    file: "https://dl.dropboxusercontent.com/scl/fi/s1501h3qltd641olzntnp/Bailey-Zimmerman-Rock-and-A-Hard-Place-Official-Music-Video.mp3?rlkey=wbcpmweq8l8v4y5volk2xydth&st=cwpwgv5i&dl=0",
    play: true,
  },
  {
    name: "Wings",
    artist: "Jackson Dean",
    file: "https://dl.dropboxusercontent.com/scl/fi/px3ctrv6l2pkhswar0n3g/Jackson-Dean-Wings-Lyric-Video.mp3?rlkey=hml7khrpyr3bd1h2rr9n4u7dw&st=k31d7p4q&dl=0",
    play: false,
  },
  {
    name: "Keep the Wolves at Bay",
    artist: "Lucius",
    file: "https://dl.dropboxusercontent.com/scl/fi/330pih6sxihvw9cvab8xm/Uncle-Lucius-Keep-The-Wolves-Away.mp3?rlkey=bmnqpwxl4gv8fxyxwupu2wsc7&st=f6ufxpid&dl=0",
    play: true,
  },
  {
    name: "Something in the Orange",
    artist: "Zach Bryan",
    file: "https://dl.dropboxusercontent.com/scl/fi/309s467dfzj9rg2b26jv0/Something-in-the-Orange.mp3?rlkey=i4di092o3nx7g286yeqgk9r1d&st=jcgav2n3&dl=0",
    play: false,
  },
  {
    name: "Glycerine",
    artist: "Bush",
    file: "https://dl.dropboxusercontent.com/scl/fi/qlellgsns6qo1gux0gow0/01-Glycerine.mp3?rlkey=dxzpjqvf68plxsjdi0j87tufp&st=g772j6bo&dl=0",
    play: false,
  },
  {
    name: "Say Something",
    artist: "Great Big World",
    file: "https://dl.dropboxusercontent.com/scl/fi/twdvxtbihcdvgn9xurgfc/Say-Something-I-m-Giving-Up-On-You-Lyrics-A-Great-Big-World-Christina-Aguilera.mp3?rlkey=4h9nc7zevccpzqpldnja15sj2&st=b7kldb9u&dl=0",
    play: false,
  },
  // {
  //   name: "After I'm Gone",
  //   artist: "Michael Bennet",
  //   file: "https://dl.dropboxusercontent.com/scl/fi/q7vgbnra1qnziwcmc0e9e/Heartbreaking-After-Im-Gone-By-MICHAEL-BENNET-Americas-Got-Talent-8-min-JER-STE-VI-HTELI.mp3?rlkey=glfdh3w4f54zid9fbwiczs9qg&st=qjp1ea41&dl=0",
  //   play: false,
  // },
  {
    name: "Tomorrow For Us",
    artist: "Jelly Roll, Rihana and Eminem",
    file: "https://dl.dropboxusercontent.com/scl/fi/e217ro2tev5gstkhj52id/Eminem-ft-Jelly-Roll-Rihanna-Tomorrow-For-Us-2026-Music-Video.mp3?rlkey=jd0v2wcd9ld49sun3z50jbvhp&st=hly9o5br&dl=0",
    play: false,
  },
  {
    name: "Im Not Ok",
    artist: "Post Malone",
    file: "https://dl.dropboxusercontent.com/scl/fi/v37zqeo8ts1bwqzj5mfur/Post-Malone-I-m-Not-Okay-Lyrics-Video.mp3?rlkey=2sw8t1m8dk75s91fmyuwbk2qk&st=daimcplw&dl=0",
    play: false,
  },
  {
    name: "Imperfections",
    artist: "Post Malone",
    file: "https://dl.dropboxusercontent.com/scl/fi/y90wdkf6o3cj65oq00yrc/Post-Malone-Imperfections-ft-Jelly-Roll-Sia-Morgan-Wallen-Official-Lyrics-Video-2026.mp3?rlkey=z19vinzn3kukjlrj5bv54r2ay&st=ot4z34xd&dl=0",
    play: false,
  },
  {
    name: "Love, Reign O'er Me",
    artist: "Pearl Jam",
    file: "https://dl.dropboxusercontent.com/scl/fi/topxoox23ka3y0q5l3keo/Love-Reign-O-er-Me-Pearl-Jam.mp3?rlkey=gws42kaz77qyeyxdq3zh8ghof&st=43hzn7g4&dl=0",
    play: false,
  },
  {
    name: "Something I Can Never Have",
    artist: "Nine Inch Nails",
    file: "https://dl.dropboxusercontent.com/scl/fi/f5tejicc3ernbftk64eve/05.-Something-I-Can-Never-Have.mp3?rlkey=rctzbwjk2m1yd8zwhd913wma5&st=101e58a7&dl=0",
    play: false,
  },
  {
    name: "Black",
    artist: "Pearl Jam",
    file: "https://dl.dropboxusercontent.com/scl/fi/wk91ez7qi9abzcydyihy5/05-Black.flac?rlkey=6iayf3an6b5jn0lxrydto4hjh&st=e3wbf2vg&dl=0",
    play: false,
  },
  {
    name: "Ran so Far Away",
    artist: "Flock of Seagulls",
    file: "https://dl.dropboxusercontent.com/scl/fi/f9dqep0z7uevwj53u4wdj/A-Flock-of-Seagulls-I-Ran-So-Far-Away.mp3?rlkey=rtqmorlwiw2t1s6ql5pdloily&st=bvhay3db&dl=0",
    play: false,
  },
  {
    name: "Behind Blue Eyes",
    artist: "Limp Bizkit",
    file: "https://dl.dropboxusercontent.com/scl/fi/vepfqfa4mgyflb2jqlu4q/1-15-Behind-Blue-Eyes.mp3?rlkey=3bcznw4uic87yg18irlzmsnzn&st=olvrvj1k&dl=0",
    play: false,
  },
  {
    name: "Bob Segar",
    artist: "Turn the Page",
    file: "https://dl.dropboxusercontent.com/scl/fi/7hi2hsrutia0llwukig3i/Bob-Seger-Turn-The-Page-1973-Radio-Version.mp3?rlkey=kfmv0ghv1ocz8qcta5fxsyhb9&st=mjzebvmq&dl=0",
    play: false,
  },
  {
    name: "Simple Man",
    artist: "Shinedown",
    file: "https://dl.dropboxusercontent.com/scl/fi/bmrblmpjar1ejg84mybrc/Shinedown-Simple-Man-Official-Video.mp3?rlkey=fosr1b69k2ihznc6lwy0iny08&st=j42xski9&dl=0",
    play: false,
  },
  {
    name: "Son of a Sinner",
    artist: "Jelly Role",
    file: "https://dl.dropboxusercontent.com/scl/fi/31m1v918h1lb11flkhcw1/Jelly-Roll-Son-Of-A-Sinner-Official-Music-Video.mp3?rlkey=2lwxzmw7milfwqvs7ul5rvddw&st=vhkuflll&dl=0",
    play: false,
  },
  {
    name: "Lose Control",
    artist: "Teddy Swimms",
    file: "https://dl.dropboxusercontent.com/scl/fi/ao4ly9jrx6pmu1s19dbyy/Teddy-Swims-Lose-Control-The-Village-Sessions.mp3?rlkey=2a1qmhu2v7xnr981atzoxv1pw&st=hjya9lrw&dl=0",
    play: false,
  },
  {
    name: "Say something Im Giving Up On You",
    artist: "Great Big World",
    file: "https://dl.dropboxusercontent.com/scl/fi/twdvxtbihcdvgn9xurgfc/Say-Something-I-m-Giving-Up-On-You-Lyrics-A-Great-Big-World-Christina-Aguilera.mp3?rlkey=4h9nc7zevccpzqpldnja15sj2&st=yirj7bwc&dl=0",
    play: false,
  },
  {
    name: "Let It Go",
    artist: "James Bay",
    file: "https://dl.dropboxusercontent.com/scl/fi/yp09m82k0cjarz4uu0sw0/James-Bay-Let-It-Go.mp3?rlkey=smkel8r90shpf7zal2cexgds4&st=c6o3u7nt&dl=0",
    play: false,
  },
  {
    name: "I Remember Everything",
    artist: "Zach Bryan",
    file: "https://dl.dropboxusercontent.com/scl/fi/a7cgaciohjxmtewip88ho/Zach-Bryan-I-Remember-Everything-feat.-Kacey-Musgraves.mp3?rlkey=9vnt020p10eqvfl0el72ay8mp&st=wcbkz6vl&dl=0",
    play: false,
  },
  {
    name: "All My Friends",
    artist: "The Revivalists",
    file: "https://dl.dropboxusercontent.com/scl/fi/8smp0gfs31e5qj4hcj3re/The-Revivalists-All-My-Friends-OFFICIAL-LYRIC-VIDEO.mp3?rlkey=j4r8j7rit4aureavjjohlmbtn&st=3efnq6wq&dl=0",
    play: false,
  },
  {
    name: "Im Not The Only One",
    artist: "Sam Smith",
    file: "https://dl.dropboxusercontent.com/scl/fi/p50v9c6mlkbi643tamust/Sam-Smith-I-m-Not-The-Only-One-Lyrics.mp3?rlkey=z2rw54zwshhf5bzobxa2bx08i&st=04aryabl&dl=0",
    play: false,
  },
  {
    name: "Have It All",
    artist: "Jason Mraz",
    file: "https://dl.dropboxusercontent.com/scl/fi/haft78fyqdgm7jy9j09nk/Have-It-All-Jason-Mraz-Lyrics.mp3?rlkey=lmiex7q8fo948q0moie30zgt2&st=akvr6xjc&dl=0",
    play: false,
  },
  {
    name: "Blurry",
    artist: "Puddle of Mud",
    file: "https://dl.dropboxusercontent.com/scl/fi/3erlr76rnzwlnjvdomp0g/Puddle-Of-Mudd-Blurry-Official-Music-Video.mp3?rlkey=tk84fnnebon5soycc0xjbnp4y&st=wvq7fk6i&dl=0",
    play: false,
  },
  {
    name: "Bother",
    artist: "Stone Sour",
    file: "https://dl.dropboxusercontent.com/scl/fi/6arbbidep1355lfn00sk4/Stone-Sour-Bother-OFFICIAL-VIDEO.mp3?rlkey=p8skoxj07wctaxzbhcb7jqk4d&st=7ie8i7es&dl=0",
    play: false,
  },
  {
    name: "Unsteady",
    artist: "X-Ambassadors",
    file: "https://dl.dropboxusercontent.com/scl/fi/cyjyblcxkpwg8dngn1y2z/X-Ambassadors-Unsteady-Lyrics-hold-on-to-me-Cause-I-m-a-little-unsteady.mp3?rlkey=cc9lql0ufnipyxx5dg72wtlho&st=oowzd91w&dl=0",
    play: false,
  },
  {
    name: "Leave A Light On",
    artist: "Papa Roach",
    file: "https://dl.dropboxusercontent.com/scl/fi/q0ee8pphahogxj1bd7r6g/Papa-Roach-Leave-A-Light-On-Talk-Away-The-Dark-Official-Live-Music-Video.mp3?rlkey=0mvp66wz6pwu0fzmi0kj5qbt7&st=e8b93aii&dl=0",
    play: false,
  },
  {
    name: "You and Me",
    artist: "Yelawolf",
    file: "https://dl.dropboxusercontent.com/scl/fi/lgf7co9hgshj8l8hmg2fk/Yelawolf-You-Me-Lyrics.mp3?rlkey=8db8vqtjz5k370fncefd6hgzx&st=g8yljyru&dl=0",
    play: false,
  },
  {
    name: "Call Me",
    artist: "Shinedown",
    file: "https://dl.dropboxusercontent.com/scl/fi/p69j3t08j4kfh34zkql0a/Shinedown-Call-Me-lyrics.mp3?rlkey=4e44ud0pkcosqkckwmy5byv1q&st=y1ys8u8t&dl=0",
    play: false,
  },
  {
    name: "Somebody Save Me",
    artist: "Eminem",
    file: "https://dl.dropboxusercontent.com/scl/fi/r1zes4c25ex0e5blelbo5/Eminem-Somebody-Save-Me-feat.-Jelly-Roll-Official-Music-Video.mp3?rlkey=rfy6ra7f9y6z5700x8h2wy4ui&st=jr64c0t1&dl=0",
    play: false,
  },
  {
    name: "Humans Being",
    artist: "Van Halen",
    file: "https://dl.dropboxusercontent.com/scl/fi/gqyclzcfcqpx12hxe6dav/Van-Halen-Humans-Being-Official-Music-Video-HD.mp3?rlkey=aopz9lhdz0xo0kctmdsktshcq&st=a5f2m81w&dl=0",
    play: false,
  },
  {
    name: "Bother",
    artist: "Stone Sour",
    file: "https://dl.dropboxusercontent.com/scl/fi/6arbbidep1355lfn00sk4/Stone-Sour-Bother-OFFICIAL-VIDEO.mp3?rlkey=p8skoxj07wctaxzbhcb7jqk4d&st=7ie8i7es&dl=0",
    play: false,
  },
  {
    name: "Blurry",
    artist: "Puddle of Mud",
    file: "https://dl.dropboxusercontent.com/scl/fi/3erlr76rnzwlnjvdomp0g/Puddle-Of-Mudd-Blurry-Official-Music-Video.mp3?rlkey=tk84fnnebon5soycc0xjbnp4y&st=0rfr1b1p&dl=0",
    play: false,
  },
  {
    name: "Too Sweet",
    artist: "Hozier",
    file: "https://dl.dropboxusercontent.com/scl/fi/ffee3lbbxo6b9yqrs9qtq/Hozier-Too-Sweet-Official-Lyric-Video.mp3?rlkey=ly1saegstvipgc95g97z0aejn&st=51kkwzxh&dl=0",
    play: false,
  },
  {
    name: "Blue Eyes",
    artist: "Dark Grunge",
    file: "https://dl.dropboxusercontent.com/scl/fi/t47z17aooxk2pl16j6b4p/Behind-Blue-Eyes-Dark-Grunge-Progressive-Rock-Original-Version.mp3?rlkey=8s1yqmum9j9gp049vwgkhzp68&st=m7ytht7y&dl=0",
    play: false,
  },
  {
    name: "Blackbird",
    artist: "Lisa O'Neill",
    file: "https://dl.dropboxusercontent.com/scl/fi/6po7aek4qorbk93gm15zn/LISA-O-NEILL-Blackbird.mp4?rlkey=flzngnkg58fzejevdr3f7n8eo&st=9yxaivuf&dl=0",
    play: false,
  },
  {
    name: "Bartholemy",
    artist: "Silent Comedy",
    file: "https://dl.dropboxusercontent.com/scl/fi/xvnvsagyxj43ui8665jwr/SilentComedy-Bartholomew.mp3?rlkey=q89o3fjx9xxgeejmb1f6xe4po&st=wujsz0rd&dl=0",
    play: false,
  },
  {
    name: "Let It Go",
    artist: "The Neighborhood",
    file: "https://dl.dropboxusercontent.com/scl/fi/1bccrx8jyvjave7na3dhi/The-Neighbourhood-Let-It-Go-Official-Video.mp3?rlkey=uzoiaj0sqk9ftgf6lsz6uqtsn&st=qadty696&dl=0",
    play: false,
  },
  {
    name: "Beggin for Thread",
    artist: "Banks",
    file: "https://dl.dropboxusercontent.com/scl/fi/11o3baie0c363e6tszsbm/The-Originals-2x03-Banks-Beggin-For-Thread.mp3?rlkey=esrpkxp04u2dju0ywhxx2l5pd&st=wb9qukgw&dl=0",
    play: false,
  },
  {
    name: "All The Debts I Owe",
    artist: "Caamp",
    file: "https://dl.dropboxusercontent.com/scl/fi/e3nkhz58kanui5eppksmg/All-the-Debts-I-Owe.mp3?rlkey=clrlo2b7m7lvunurthbkacdjy&st=lervk1cf&dl=0",
    play: false,
  },
  {
    name: "I Feel Love",
    artist: "Donna Summer",
    file: "https://dl.dropboxusercontent.com/scl/fi/8k3qbh5doqix5tk0rzqsy/i-Feel-Love-DS.mp3?rlkey=2ut9uj4u23f5e2yqpz62tlh07&st=ech0puar&dl=0",
    play: false,
  },
  {
    name: "Seven Years",
    artist: "Natalie Merchant",
    file: "https://dl.dropboxusercontent.com/scl/fi/xqcha53u88nmisrd9g4um/Seven-Years.mp3?rlkey=h943majazlaa5i5rnrt1pazn8&st=q58to8qq&dl=0",
    play: false,
  },
  {
    name: "Someone You Loved",
    artist: "Lewis Capaldi",
    file: "https://dl.dropboxusercontent.com/scl/fi/id30dd2gigmccl3zxvhx4/03.-Someone-You-Loved.mp3?rlkey=f6ivjlv8gj75y3uh88k6p15si&st=tv6t1k0j&dl=0",
    play: false,
  },
  {
    name: "Chasing Cars",
    artist: "Snow Patrol",
    file: "https://dl.dropboxusercontent.com/scl/fi/0x0m2p0sejnaig81lf28r/Snow-Patrol-Chasing-Cars.mp3?rlkey=96buto719q66udi7ixdp2vp5i&st=qti7cgdc&dl=0",
    play: false,
  },
  {
    name: "The Silence",
    artist: "Manchester Orchestra",
    file: "https://dl.dropboxusercontent.com/scl/fi/hzl7bhuigqc1vc79yxfuh/Manchester-Orchestra-The-Silence-Official-Music-Video.mp3?rlkey=s0fv1cx3lx0jcdh4b6pxb2pbx&st=k2uim51n&dl=0",
    play: false,
  },
  {
    name: "Bring It On",
    artist: "Nick Cave & The Bad Seeds",
    file: "https://dl.dropboxusercontent.com/scl/fi/p74q6u0aiq2uy4vf8iqno/Nick-Cave-The-Bad-Seeds-Bring-It-On-Official-Audio.mp3?rlkey=jen74ebvq3vetiiracwmddf1m&st=gnwlw5ot&dl=0",
    play: false,
  },
  {
    name: "Red Right Hand",
    artist: "Nick Cave & The Bad Seeds",
    file: "https://dl.dropboxusercontent.com/scl/fi/g2nfnqwcuh7kcy2l3u9j1/Nick-Cave-The-Bad-Seeds-Red-Right-Hand.mp3?rlkey=gx2y1l6mljphu71pgsiwuirto&st=a20vcc84&dl=0",
    play: false,
  },
  {
    name: "You Want It Darker",
    artist: "Leonard Cohen",
    file: "https://dl.dropboxusercontent.com/scl/fi/bjzb6t1gv9to07sw7t0ax/Leonard-Cohen-You-Want-It-Darker-Official-Audio.mp3?rlkey=w0b0nav9yg2tuahcw8igynykw&st=7oviorkv&dl=0",
    play: false,
  },
  {
    name: "Crossfire",
    artist: "Stevie Ray Vaughan",
    file: "https://dl.dropboxusercontent.com/scl/fi/mp6z7fmsswx3mpyh6d4ex/Stevie-Ray-Vaughan-Crossfire-Official-Video.mp3?rlkey=os91mgfzwe76jkh385uq87gy1&st=0rdhabr9&dl=0",
    play: false,
  },
  {
    name: "Voodoo Child (Slight Return)",
    artist: "Jimi Hendrix",
    file: "https://dl.dropboxusercontent.com/scl/fi/shuud6haw4dpoz6iiqjqm/Voodoo-Child-Slight-Return.mp3?rlkey=khn88jynnx5waruhu8jsrypiq&st=fu4z3t65&dl=0",
    play: false,
  },
  {
    name: "Sympathy For The Devil",
    artist: "The Rolling Stones",
    file: "https://dl.dropboxusercontent.com/scl/fi/gnfx8wgdxdvws5q2ls1un/The-Rolling-Stones-Sympathy-For-The-Devil-Official-Video-4K.mp3?rlkey=m1rligrw6rrm70dcj0kzm1a64&st=jb23m8be&dl=0",
    play: false,
  },
  {
    name: "Pride and Joy",
    artist: "Stevie Ray Vaughan",
    file: "https://dl.dropboxusercontent.com/scl/fi/asaxkt0weg81uzg4xokte/Stevie-Ray-Vaughan-Pride-and-Joy-Studio-version.mp3?rlkey=aqm7r05237cllo1qtar9w4ts1&st=srk4be41&dl=0",
    play: false,
  },
  {
    name: "Empty Chair",
    artist: "Afriafri",
    file: "https://dl.dropboxusercontent.com/scl/fi/qpw64t7246s6qnkhlob6e/Empty-Chair.mp3?rlkey=ee15syr6xumbc7os2rgtkug3e&st=xaqvpm5m&dl=0",
    play: false,
  },
  {
    name: "Gimme Shelter",
    artist: "The Rolling Stones",
    file: "https://dl.dropboxusercontent.com/scl/fi/gini8jgkomly954m2tgvj/The-Rolling-Stones-Gimme-Shelter-Official-Lyric-Video.mp3?rlkey=7bdf1kpv1riyz6zcxflkamj01&st=57cutoh9&dl=0",
    play: false,
  },
  {
    name: "Sympathy For The Devil",
    artist: "The Rolling Stones",
    file: "https://dl.dropboxusercontent.com/scl/fi/gnfx8wgdxdvws5q2ls1un/The-Rolling-Stones-Sympathy-For-The-Devil-Official-Video-4K.mp3?rlkey=m1rligrw6rrm70dcj0kzm1a64&st=90g7s4e5&dl=0",
    play: false,
  },
  {
    name: "Sail",
    artist: "AWOLNATION",
    file: "https://dl.dropboxusercontent.com/scl/fi/kjn77d58j742ka3i6s3wc/10-Sail.mp3?rlkey=u151rtb7mfhi9nfox0mmxtz0l&st=zkq4gvr4&dl=0",
    play: false,
  },
  {
    name: "Is There A Ghost",
    artist: "Band of Horses",
    file: "https://dl.dropboxusercontent.com/scl/fi/a18h6sxanjmcfvel1giz5/Is-There-A-Ghost.mp3?rlkey=3pdwmgydsxu1gxzrknwm2onhf&st=ze3cf4sp&dl=0",
    play: false,
  },
  {
    name: "Sunglasses at Night",
    artist: "Corey Hart",
    file: "https://dl.dropboxusercontent.com/scl/fi/5nrq2krf9ctwvrormy3qz/Corey-Hart-Sunglasses-at-Night-HQ.mp3?rlkey=05ceypuk7ngtown0kkp7231g9&st=0jzqfb55&dl=0",
    play: false,
  },
  {
    name: "No Plan",
    artist: "Hozier",
    file: "https://dl.dropboxusercontent.com/scl/fi/pr0rr6znr87313ib6r2nx/Hozier-No-Plan.mp3?rlkey=rb8vr8jzlv89zn1zj6r8jy0hw&st=ye8vja1w&dl=0",
    play: false,
  },
  {
    name: "Arsonist's Lullabye",
    artist: "Hozier",
    file: "https://dl.dropboxusercontent.com/scl/fi/mu3zt2xrjcah1b1eye4py/2-03-Arsonist-s-Lullabye.mp3?rlkey=34nm3fe3khsmpi7t3unbkfa02&st=yoo8e8ln&dl=0",
    play: false,
  },
  {
    name: "Beggin For Thread",
    artist: "Banks",
    file: "https://dl.dropboxusercontent.com/scl/fi/11o3baie0c363e6tszsbm/The-Originals-2x03-Banks-Beggin-For-Thread.mp3?rlkey=esrpkxp04u2dju0ywhxx2l5pd&st=76cc7d5x&dl=0",
    play: false,
  },
  {
    name: "Long Time Traveller",
    artist: "Wailing Jennys",
    file: "https://dl.dropboxusercontent.com/scl/fi/skdgmkfivjzosvlgum9ep/Long-Time-Traveller-wailingJennys.mp3?rlkey=qc78f5wj7vw5vq379vycg5b3d&st=bl8cmprq&dl=0",
    play: false,
  },
  {
    name: "Im Only Joking",
    artist: "Kongos",
    file: "https://dl.dropboxusercontent.com/scl/fi/ni6w5cfse0bmh6jpp8r6l/01-I-m-Only-Joking.mp3?rlkey=93353hg6yfamidx8hw6vr6h87&st=b8isvwnc&dl=0",
    play: false,
  },
  {
    name: "Come ith Me Now",
    artist: "Kongos",
    file: "https://dl.dropboxusercontent.com/scl/fi/gvrdkr1o07zjagvmmzu5v/02-Come-With-Me-Now.mp3?rlkey=7m4l5t2s97ve8ygfuwwk85ib6&st=wsx4sj7j&dl=0",
    play: false,
  },
  {
    name: "Bartholomew",
    artist: "Silent Comedy",
    file: "https://dl.dropboxusercontent.com/scl/fi/0y3vgv2mfbpib7z54mt07/SilentComedy-Bartholomew.mp3?rlkey=t96d1s6xyr7xfdwqcakkti7gf&st=odi8iomu&dl=0",
    play: false,
  },
  {
    name: "Let It Go",
    artist: "The Neighborhood",
    file: "https://dl.dropboxusercontent.com/scl/fi/z1dhmlfkolf3d1i13tdvx/The-Neighbourhood-Let-It-Go-Official-Video.mp3?rlkey=npnr836cvzx3sjkzeju7441ev&st=u7hr0rbt&dl=0",
    play: false,
  },
  {
    name: "Violets Tale",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/qqzbwlyqn75dxrkweznyl/Violets-Tale-Official-Music-Video.mp3?rlkey=qri3g7ybaqze5mal8wh7wegnr&st=m6b4fraj&dl=0",
    play: false,
  },
  {
    name: "Vincents Tale - Sunflowers",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/0e4d1g8y8gcqlje6gh77g/Vincents-Tale-Sunflowers-Prologue.mp3?rlkey=bbnk8om0sxi1phunfdddxfd9k&st=lnt0zom4&dl=0",
    play: false,
  },
  {
    name: "Suicide",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/s3rhe0gyhkpf3o6zyzuoj/Su-cIde-Official-Music-Video.mp3?rlkey=fjmbnlwlqd39b29cbzm44es02&st=0g33vzst&dl=0",
    play: false,
  },
  {
    name: "The Big Push",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/jct3nsjaalkj1ctvt8hdw/The-Big-Push.-24.mp3?rlkey=v3iqgz5ppgobfsvg0ax038na6&st=ux5qk4h2&dl=0",
    play: false,
  },
  {
    name: "Money Game Part 3",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/4n105lghzn5ugpbsqlovx/Money-Game-Part-3-Official-Music-Video.mp3?rlkey=jsmqzfdgvuyyfiewhqayn06s7&st=c43hmt30&dl=0",
    play: false,
  },
  {
    name: "I shot the Sheriff",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/reeftupj6hsokvoxsu06f/I-Shot-the-Sheriff_Road-to-Zion_Hip-Hop.mp3?rlkey=rebylauduznkl3sbvc6sqslbd&st=l9lrle7c&dl=0",
    play: false,
  },
  {
    name: "In in Love",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/ysaivmhs6vxca639addxd/Im-in-love.mp3?rlkey=sdvdpbu1fitkhwvpgael2ginh&st=2kwm8gm3&dl=0",
    play: false,
  },
  {
    name: "Jenney's Tale",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/3qj481r5eew4bl9xmi7u8/Jennys-Tale-Official-Music-Video.mp3?rlkey=sfdz1923gd5kjngyhu28iowqb&st=6kqmpcge&dl=0",
    play: false,
  },
  {
    name: "How to be Me",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/zvlzzn3lqana5z5jujzeb/How-To-Be-Me-Lyric-Video.mp3?rlkey=3qtjntosjs05gug76ztr4pi5m&st=146lo59a&dl=0",
    play: false,
  },
  {
    name: "Hi Ren",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/ti30vw36e3cvabpsuy6pj/Hi-Ren.mp3?rlkey=0o7hhz8mz2kdfzxzfsfoqd86j&st=mfbdfbti&dl=0",
    play: false,
  },
  {
    name: "It's a Mans World",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/e78y7lei6u9is0d8lki49/Earned-it-_Mans-World-_-Falling.mp3?rlkey=2flpgxnpnl54hrno9zrlmo7py&st=izaqds3f&dl=0",
    play: false,
  },
  {
    name: "Chalk Outlines",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/g8tq8xd1c6tqzll59cy6o/Chalk-Outlines-Official-Lyrics-Video.mp3?rlkey=9h4spfb4yv3hess2iy0idvlt8&st=xgsw9vs5&dl=0",
    play: false,
  },
  {
    name: "Blind Eyed",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/b9yqwu49w4zad2z8to77u/Blind-Eyed-Live-Performance.mp3?rlkey=6o2fd85pn33ei21x3gndgz482&st=tqg9blfv&dl=0",
    play: false,
  },
  {
    name: "Power",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/v2fh2i3jyal7yh8m3w2fp/Ren-Power-Official-Music-Video.mp3?rlkey=y1s4x1o556vhm7yow6gzv5t9a&st=wtkwzsxk&dl=0",
    play: false,
  },
  {
    name: "Murderer",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/kzrlpu4awms4np9id26df/Ren-Murderer-Official-Music-Video.mp3?rlkey=6l0uq6hnc6fyhsh14g3onqmen&st=bxkh6kos&dl=0",
    play: false,
  },
  {
    name: "Kujo Beat Down",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/v2tbrf52qkqc9ff2blr46/Ren-KUJO-BEAT-DOWN.mp3?rlkey=wquzgn2pqml3918gxm1fhxcjl&st=9z6et0w3&dl=0",
    play: false,
  },
  {
    name: "Angels above Me",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/1dr1s8yxcomnx5gtvu0ph/Angels-Above-Me.mp3?rlkey=4yffr5w6ktlpe3xyh4gccti30&st=5nu0ieve&dl=0",
    play: false,
  },
  {
    name: "Sentenced",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/55ga064vvtfb0jurvl19w/Stick-Figure-_Sentenced_.mp3?rlkey=9x2mi7tiw5qukp5v1at3zhbfv&st=wqpxbbz1&dl=0",
    play: false,
  },
  {
    name: "Out the Door",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/bhrysw9i5cwaiacakszfg/Stick-Figure-_Out-the-Door_.mp3?rlkey=gh897zk6vm050q1nvke1y53zi&st=7rhcmox0&dl=0",
    play: false,
  },
  {
    name: "One of Those Days",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/b75vgttt6klptvjzk1tyc/Stick-Figure-_One-of-Those-Days_.mp3?rlkey=kqsjpvyuxm8wq3xtwjh039e7x&st=czoryrhf&dl=0",
    play: false,
  },
  {
    name: "Mind Block",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/of4gsq359uteca7egaykl/Stick-Figure-_Mind-Block_-feat.-E.mp3?rlkey=k8j0gnzim44f1343n0d13r1jz&st=9rqrokaj&dl=0",
    play: false,
  },
  {
    name: "Set in Stone (Full Album).mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/bwsfmtiurtt5yf54gnj21/Set-in-Stone-Full-Album.mp3?rlkey=f971zpil07899qh1egliwgrs4&st=amluk4p2&dl=0",
    play: false,
  },
  {
    name: "All My Love",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/s9w8ap91xpe8oommo6jm2/Stick-Figure-_All-My-Love_.mp3?rlkey=is4moocbsrojxn50hhgty37cz&st=j4pl9yw4&dl=0",
    play: false,
  },
  {
    name: "14 Smiles on Faces.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/cbh9640gfnh9amrka849a/14-Smiles-on-Faces.mp3?rlkey=m509r61p3fos00q1zolp92l6u&st=qwbxppgu&dl=0",
    play: false,
  },
  {
    name: "13 Sunshine and Rain.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/w3ryfbeajxopp634144i1/13-Sunshine-and-Rain.mp3?rlkey=a2d9qbogyg3fjpf1v6sktfppt&st=mpbd3ovv&dl=0",
    play: false,
  },
  {
    name: "09 Smoking Love.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/k06catv2kole6hfmza49i/09-Smoking-Love.mp3?rlkey=gtyetza3zwdfjhijxnezkld01&st=ng4jlk47&dl=0",
    play: false,
  },
  {
    name: "08 Weary Eyes.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/1fb1q2yh7csskk7gghypr/08-Weary-Eyes.mp3?rlkey=264n9z3wb5n71ed5sj69hm2w2&st=995l9rkj&dl=0",
    play: false,
  },
  {
    name: "04 Choice is Yours.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/ouk1uxan2heevqmjp5czk/04-Choice-is-Yours.mp3?rlkey=hxyz388oivhaeafw0yb0f5j4h&st=wciqxom3&dl=0",
    play: false,
  },
  {
    name: "03 Sound of the Sea.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/0wlumviegax4uhy0ez3v7/03-Sound-of-the-Sea.mp3?rlkey=pprjoii4bt0w99sjaq2mndhu1&st=zsyx3s02&dl=0",
    play: false,
  },
  {
    name: "01 Fire On the Horizon.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/9amwh15zbgdaz2c0s4tv6/01-Fire-On-the-Horizon.mp3?rlkey=iqls4t4fm0h5d8l59x33i7jyw&st=iu5ib4fo&dl=0",
    play: false,
  },
  {
    name: "02 In This Love.mp3",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/vmpevxrwl7d25htmrt2ph/12-Wonderful-World.mp3?rlkey=tbgv82u04cw3ytow86ncnkw2l&st=jznkl2sf&dl=0",
    play: false,
  },
  {
    name: "02 Is This Love",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/s148hu74euom9yrjejx0u/02-In-This-Love.mp3?rlkey=xeuq7xs7rm7d03ouzxj1gh2ef&st=gtj9qx4m&dl=0",
    play: false,
  },
  {
    name: "World on Fire - Full Album",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/mvky96b4b4lokl96x4npa/World-on-Fire-Full-Album.mp3?rlkey=cpr0i61legcj8mwqf1n0fkt22&st=78h0kpce&dl=0",
    play: false,
  },
  {
    name: "White Fire",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/1y9v8rkynbg5pnuumz6h7/01-White-Fire.mp3?rlkey=z5lj704nppx36l0i3kxv9jdpn&st=owm4kcv3&dl=0",
    play: false,
  },
  {
    name: "We Get High",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/ppvwnxx6xv7cajptgrlh1/02-We-Get-High.mp3?rlkey=zmom49ke5584ued4dpuipns10&st=7af8el45&dl=0",
    play: false,
  },
  {
    name: "Trouble Up There",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/tnpwuobiwbh92d17ail59/03-Trouble-Up-There.mp3?rlkey=om9dps4br8lis419p9om370yb&st=wd82a9lo&dl=0",
    play: false,
  },
  {
    name: "Dead End Street",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/ajoqzgw6cwswognf0e41g/04-Dead-End-Street.mp3?rlkey=vlukkvg04416myauddtg06st1&st=xlznl4yt&dl=0",
    play: false,
  },
  {
    name: "Running Wild",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/wehvuwyxalyyp2xnbuy4h/05-Running-Wild.mp3?rlkey=r9j6zjzf2t1qtf4hklnttx0dn&st=rk473gl0&dl=0",
    play: false,
  },
  {
    name: "The World is Waiting",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/j2zs90ma39rx9dnynk9bc/06-The-World-is-Waiting.mp3?rlkey=3rjhb32xiwmxlblji0pd3nl0i&st=icyxwr1f&dl=0",
    play: false,
  },
  {
    name: "Burnin Ocean",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/fq1z081gfokdwylp1j4m0/07-Burnin-Ocean.mp3?rlkey=g745v5dn9obkzqx5hax3yt57i&st=mje6zeay&dl=0",
    play: false,
  },
  {
    name: "So Good",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/9cvfj3e5cgvgtaygquco4/08-So-Good.mp3?rlkey=ih4nhpfrac1w9un8ehy4he63w&st=mft0s8wl&dl=0",
    play: false,
  },
  {
    name: "Come With Me",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/26u58vhlfei72sdup79v2/09-Come-With-Me.mp3?rlkey=mrg8eaeom9srzymw223exausa&st=lwyyap56&dl=0",
    play: false,
  },
  {
    name: "Rise Above",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/g866gzvwxah6a86f71rr1/10-Rise-Above.mp3?rlkey=k6k1qd9b79txmdwtgrjdnogba&st=ky457g6j&dl=0",
    play: false,
  },
  {
    name: "Ballz Deep",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/wyzroppszbiwm8tdgk7ig/11-Ballz-Deep.mp3?rlkey=neamnwxl66gjc7flgoaxcdp3o&st=hcpyxl7d&dl=0",
    play: false,
  },
  {
    name: "Wonderful World",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/vmpevxrwl7d25htmrt2ph/12-Wonderful-World.mp3?rlkey=tbgv82u04cw3ytow86ncnkw2l&st=jznkl2sf&dl=0",
    play: false,
  },
  {
    name: "Love Found",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/e8om0oyc9dpckoh2sms7n/13-Love-Found.mp3?rlkey=95qydu1rc4p2yiwwyhn80wf3q&st=nmz5cmd1&dl=0",
    play: false,
  },
  {
    name: "Songs of Yesterday",
    artist: "Stick Figure",
    file: "https://dl.dropboxusercontent.com/scl/fi/5gg9k7epb5jflnzix4qrl/14-Songs-of-Yesterday.mp3?rlkey=xf61sizy6ry1j6nyjutj6tgc6&st=b64mlq6x&dl=0",
    play: false,
  },

  {
    name: "Always on my Mind",
    artist: "Leire",
    file: "https://dl.dropboxusercontent.com/scl/fi/1pe4el6v88tk19sm2t8u9/Youre-Always-On-My-Mind-Willie-Nelson-Cover.mp3?rlkey=a2lbuldbwouur9uavvimqzs3r&st=tdjarokv&dl=0",
    play: false,
  },
  {
    name: "Let it Be",
    artist: "Leire",
    file: "https://dl.dropboxusercontent.com/scl/fi/6r4saqyycsitlq7ith3oy/Let-It-Be-Beathes-Cover.mp3?rlkey=fekaabx6c0yc11dj7l4krvso2&st=i55l75ev&dl=0",
    play: false,
  },
  {
    name: "Skyfall",
    artist: "Leire",
    file: "https://dl.dropboxusercontent.com/scl/fi/utiilekd5d1sg638smn4d/Adele-Skyfal-Coverl.mp3?rlkey=82wl17rgg1qjv99i48jg8gde7&st=y4hfch41&dl=0",
    play: false,
  },
  {
    name: "Wicked Game",
    artist: "Leire",
    file: "https://dl.dropboxusercontent.com/scl/fi/wk9o6e093n73sxh3bmodg/Wicked-Game-Cover.mp3?rlkey=x4032ou1dsc4d90tjn9l1ewah&st=ag14v1j5&dl=0",
    play: false,
  },
  {
    name: "I Shot the Sheriff",
    artist: "Leire",
    file: "https://dl.dropboxusercontent.com/scl/fi/65d73hqq2bvn41peihlts/Knockin-On-Heavens-Door-Cover.mp3?rlkey=55zwqdbsd2a5ne9wnv9wsretw&st=1ejr432q&dl=0",
    play: false,
  },
  {
    name: "Unbreakable",
    artist: "Fireflight",
    file: "https://dl.dropboxusercontent.com/scl/fi/kupg0tpkhh5fd18d1lg4d/Fireflight-Unbreakable.mp3?rlkey=21z75fsevnrculttytgde0kwf&st=ehi40j5f&dl=0",
    play: false,
  },
  {
    name: "Not Dead Yet",
    artist: "Ledger",
    file: "https://dl.dropboxusercontent.com/scl/fi/ly9yp3t7zcuh4pikzxv05/LEDGER_-Not-Dead-Yet-OFFICIAL-VIDEO.mp3?rlkey=uva6d4kkctjxzvemqzoq6tmey&st=gm4usl9f&dl=0",
    play: false,
  },
  {
    name: "All Around Me",
    artist: "Flyleaf",
    file: "https://dl.dropboxusercontent.com/scl/fi/k5gpk70im8y8o2naod2lo/Flyleaf-All-Around-Me-Official-Music-Video.mp3?rlkey=2bkxrqckz7kx14b3js13dg3n8&st=awwyx3q8&dl=0",
    play: false,
  },
  {
    name: "You Decide",
    artist: "Fireflight",
    file: "https://dl.dropboxusercontent.com/scl/fi/r8qmkh1hl8p6rc6ujzroc/Fireflight-You-Decide.mp3?rlkey=d07qr9h7k952nglybuyi7ghsa&st=o7h4lcba&dl=0",
    play: false,
  },
  {
    name: "Ignite",
    artist: "Alan Walker",
    file: "https://dl.dropboxusercontent.com/scl/fi/i41uob6bqj811vrgn3dlw/10.-Ignite.mp3?rlkey=dhvdsqvqd87eshf41o20gn97v&st=llnc3ngc&dl=0",
    play: false,
  },
  {
    name: "Legends Never Die",
    artist: "Alan Walker",
    file: "https://dl.dropboxusercontent.com/scl/fi/pzn44dxy4j2itlitzddgt/13.-Legends-Never-Die.mp3?rlkey=f239d9867lupk8g4dh23n63ob&st=aiihb0z9&dl=0",
    play: false,
  },
  {
    name: "Green Eyes",
    artist: "Coldplay",
    file: "https://dl.dropboxusercontent.com/scl/fi/s37yyp1nawvdkm455r1bc/07-Green-Eyes.mp3?rlkey=00ko3lbh1dmkchdgku51usxg4&st=p6mconzo&dl=0",
    play: false,
  },
  {
    name: "Violets Tale",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/qqzbwlyqn75dxrkweznyl/Violets-Tale-Official-Music-Video.mp3?rlkey=qri3g7ybaqze5mal8wh7wegnr&st=m6b4fraj&dl=0",
    play: false,
  },
  {
    name: "Vincents Tale - Sunflowers",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/0e4d1g8y8gcqlje6gh77g/Vincents-Tale-Sunflowers-Prologue.mp3?rlkey=bbnk8om0sxi1phunfdddxfd9k&st=lnt0zom4&dl=0",
    play: false,
  },
  {
    name: "Suicide",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/s3rhe0gyhkpf3o6zyzuoj/Su-cIde-Official-Music-Video.mp3?rlkey=fjmbnlwlqd39b29cbzm44es02&st=0g33vzst&dl=0",
    play: false,
  },
  {
    name: "The Big Push",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/jct3nsjaalkj1ctvt8hdw/The-Big-Push.-24.mp3?rlkey=v3iqgz5ppgobfsvg0ax038na6&st=ux5qk4h2&dl=0",
    play: false,
  },
  {
    name: "Money Game Part 3",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/4n105lghzn5ugpbsqlovx/Money-Game-Part-3-Official-Music-Video.mp3?rlkey=jsmqzfdgvuyyfiewhqayn06s7&st=c43hmt30&dl=0",
    play: false,
  },
  {
    name: "I shot the Sheriff",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/reeftupj6hsokvoxsu06f/I-Shot-the-Sheriff_Road-to-Zion_Hip-Hop.mp3?rlkey=rebylauduznkl3sbvc6sqslbd&st=l9lrle7c&dl=0",
    play: false,
  },
  {
    name: "In in Love",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/ysaivmhs6vxca639addxd/Im-in-love.mp3?rlkey=sdvdpbu1fitkhwvpgael2ginh&st=2kwm8gm3&dl=0",
    play: false,
  },
  {
    name: "Jenney's Tale",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/3qj481r5eew4bl9xmi7u8/Jennys-Tale-Official-Music-Video.mp3?rlkey=sfdz1923gd5kjngyhu28iowqb&st=6kqmpcge&dl=0",
    play: false,
  },
  {
    name: "How to be Me",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/zvlzzn3lqana5z5jujzeb/How-To-Be-Me-Lyric-Video.mp3?rlkey=3qtjntosjs05gug76ztr4pi5m&st=146lo59a&dl=0",
    play: false,
  },
  {
    name: "Hi Ren",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/ti30vw36e3cvabpsuy6pj/Hi-Ren.mp3?rlkey=0o7hhz8mz2kdfzxzfsfoqd86j&st=mfbdfbti&dl=0",
    play: false,
  },
  {
    name: "It's a Mans World",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/e78y7lei6u9is0d8lki49/Earned-it-_Mans-World-_-Falling.mp3?rlkey=2flpgxnpnl54hrno9zrlmo7py&st=izaqds3f&dl=0",
    play: false,
  },
  {
    name: "Chalk Outlines",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/g8tq8xd1c6tqzll59cy6o/Chalk-Outlines-Official-Lyrics-Video.mp3?rlkey=9h4spfb4yv3hess2iy0idvlt8&st=xgsw9vs5&dl=0",
    play: false,
  },
  {
    name: "Blind Eyed",
    artist: "Ren",
    file: "https://dl.dropboxusercontent.com/scl/fi/b9yqwu49w4zad2z8to77u/Blind-Eyed-Live-Performance.mp3?rlkey=6o2fd85pn33ei21x3gndgz482&st=tqg9blfv&dl=0",
    play: false,
  },
  {
    name: "You are the Best Thing",
    artist: "Ray LaMontagne",
    file: "https://dl.dropboxusercontent.com/scl/fi/i5xdzeqbmgjhyhyc11r9x/01-You-Are-the-Best-Thing.mp3?rlkey=nxnegc9sbpr4un7ptagw8xnnq&st=f3ya5ih3&dl=0",
    play: false,
  },
  {
    name: "Don't Stop Believin'",
    artist: "Journey",
    file: "https://dl.dropboxusercontent.com/scl/fi/fhim6y5lmtjzii5qrh13q/05-Don-t-Stop-Believin.mp3?rlkey=sm3z8rje5ougtzrjf8ew5zb29&st=xqjvtzt7&dl=0",
    play: false,
  },
  {
    name: "Mamma Mia",
    artist: "ABBA",
    file: "https://dl.dropboxusercontent.com/scl/fi/3zjh1qtr0nvcz27qjdvc3/01-Mamma-Mia.mp3?rlkey=y8ds8ttur4auck1gxgejgc44m&st=pa8j4knz&dl=0",
    play: false,
  },
  {
    name: "I wanna know what love is",
    artist: "Foreigner",
    file: "https://dl.dropboxusercontent.com/scl/fi/hjggc3qc0pfo4jfjgcrwt/1-286-I-Want-to-Know-What-Love-Is-1.mp3?rlkey=g2fv6c0dhbr3gjlmmtomxbra8&st=hyb9foj1&dl=0",
    play: false,
  },
  {
    name: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/14o4ugl7nyq3a0persu1z/04-Goodbye-Yellow-Brick-Road.mp3?rlkey=02gyozmqwaw1dbpftds19vz04&st=d6pq86s2&dl=0",
    play: false,
  },
  {
    name: "Nikita",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/ysmqippk32bi3x8ygs4ts/05-Nikita.mp3?rlkey=dw3hc6qsgpe5bxa04hcup9hs4&st=1w4yzsve&dl=0",
    play: false,
  },
  {
    name: "I'm Still Standing",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/z364l2wca993g7mtex1nz/06-I-m-Still-Standing.mp3?rlkey=glcstbuii9ws5hdzsucauas25&st=jhymve8o&dl=0",
    play: false,
  },
  {
    name: "Dont Stop Me Now",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/5kwogfiq2s36duvzz1ucj/07-Don-t-Stop-Me-Now.mp3?rlkey=3y8illq1qg8ridtnebuz63b6y&st=alfqncgw&dl=0",
    play: false,
  },
  {
    name: "Don't Go Breaking My Heart",
    artist: "Elton John & Kiki Dee",
    file: "https://dl.dropboxusercontent.com/scl/fi/kttxj718kz76t95vgl71g/08-Don-t-Go-Breaking-My-Heart-Remas.mp3?rlkey=qitwi8hocyv83921td7cdzqyf&st=8uwbkll9&dl=0",
    play: false,
  },
  {
    name: "Shallow",
    artist: "Lady Gaga & Bradley Cooper",
    file: "https://dl.dropboxusercontent.com/scl/fi/685ai8d7fjxp6bb96vaxc/12-Shallow.mp3?rlkey=zerya1ruxfd08u6oio2tqjocu&st=9u6eu3jv&dl=0",
    play: false,
  },
  {
    name: "Music To My Eyes",
    artist: "Lady Gaga & Bradley Cooper",
    file: "https://dl.dropboxusercontent.com/scl/fi/sd80tzehqby2k6ge94p2h/14-Music-To-My-Eyes.mp3?rlkey=hnmsywz29bxm8qw10b9hxp3pz&st=0uhx5xi1&dl=0",
    play: false,
  },
  {
    name: "Always Remember Us This Way",
    artist: "Lady Gaga and Bradley Cooper",
    file: "https://dl.dropboxusercontent.com/scl/fi/v5folu118b2l2e8ea12ik/17-Always-Remember-Us-This-Way.mp3?rlkey=ftzsk8y3r565tnjh3p6770f97&st=6w2bfypi&dl=0",
    play: false,
  },
  {
    name: "We Are the Champions",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/fl063q39qp0rdi1wxlymq/17-We-Are-the-Champions.mp3?rlkey=jzecp7cormbp1gnip0x4w7rjw&st=629w6nt0&dl=0",
    play: false,
  },
  {
    name: "Hotel California",
    artist: "Eagles",
    file: "https://dl.dropboxusercontent.com/scl/fi/vpnfv8h7en7szakw2ew1x/01-Hotel-California.mp3?rlkey=9ametm3qzjq98p09ymt0gw5py&st=zc0ccr8q&dl=0",
    play: false,
  },
  {
    name: "Rocketman",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/lx5231jlxosz6mqjwdlje/01-Rocket-Man-I-Think-It-s-Going-to.mp3?rlkey=gyxy0cmn6h75ffpoax2wmwu5j&st=lqmwbojo&dl=0",
    play: false,
  },
  {
    name: "Somewhere Over the Rainbow",
    artist: "Israel Kamakawiwoole",
    file: "https://dl.dropboxusercontent.com/scl/fi/lc7lvxpna6lgd0e5vij8d/Over-the-Rainbow-BrotherIs.mp3?rlkey=w6fhadp0amlkfgklqom2oqwjc&st=p0ryij8l&dl=0",
    play: false,
  },
  {
    name: "Free to wear sunscreen",
    artist: "Baz Luhrman",
    file: "https://dl.dropboxusercontent.com/scl/fi/k5anr05xp6hqmiltvmejc/01-Everybody-s-Free-To-Wear-Sunscreen-Edit.mp3?rlkey=1r8dma9sm32jbm6qj6ao2hqhy&st=6gyim8to&dl=0",
    play: false,
  },
  {
    name: "Wonderful",
    artist: "Tones & I",
    file: "https://dl.dropboxusercontent.com/scl/fi/23qr9l36ayox3vw7jxsla/07.-Wonderful.mp3?rlkey=vfrqrxdtebr8mf33ijhuvh8gj&st=tkfaw7ep&dl=0",
    play: false,
  },
  {
    name: "I Will Survive",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/6f8sfx7o3b632k9fsinu6/07-I-Will-Survive.mp3?rlkey=47i4zhrzecz67sop8xkx0is4j&st=3v9v3s8y&dl=0",
    play: false,
  },
  {
    name: "Never Enough",
    artist: "Loren Allred",
    file: "https://dl.dropboxusercontent.com/scl/fi/354m6t1yvo7ptwunm0fn2/1-06-Never-Enough.mp3?rlkey=aexgktj1e4kqele6m51pixy7b&st=cbb6px3c&dl=0",
    play: false,
  },
  {
    name: "Sail Away",
    artist: "David Gray",
    file: "https://dl.dropboxusercontent.com/scl/fi/p9o0aotznrabhcodozr2w/09-Sail-Away.mp3?rlkey=1xiomfopplzptdmwuj3ll68pl&st=ujh7d4ur&dl=0",
    play: false,
  },
  {
    name: "Takes a lot to know a Man",
    artist: "Damien Rice",
    file: "https://dl.dropboxusercontent.com/scl/fi/f2br1lb70rzvxhafhn3hb/02-It-Takes-a-Lot-to-Know-a-Man.mp3?rlkey=nkar2lq8z19fvvjt61dsg2q9g&st=oxesl61a&dl=0",
    play: false,
  },
  {
    name: "Better Together",
    artist: "Jack Johnson",
    file: "https://dl.dropboxusercontent.com/scl/fi/1krmjt0fb3rox46fjkkjj/01-Better-Together.mp3?rlkey=vw7zth9naj4t5gfjmstc467f0&st=ywp7byzh&dl=0",
    play: false,
  },
  {
    name: "Love you Madly",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/5tcohtntpa2rh2gfizkuh/09-Love-You-Madly.mp3?rlkey=kmiu63sgy1i4jtxql6m77k564&st=vojf2ufc&dl=0",
    play: false,
  },
  {
    name: "Short Skirt, Long Jacket",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/7fakohoy18rsqvt0tdge8/04-Short-Skirt_Long-Jacket.mp3?rlkey=aaqamzt2dmrxpnsyijvquxjoa&st=p7fo25nr&dl=0",
    play: false,
  },
  {
    name: "Cat People - Putting Out Fire",
    artist: "David Bowie",
    file: "https://dl.dropboxusercontent.com/scl/fi/zqap5gxnnexch1rengisb/1-663-Cat-People-Putting-Out-Fire.mp3?rlkey=ywphbhljjil7pginrn40hmu87&st=0ob3m5ga&dl=0",
    play: false,
  },
  {
    name: "Perhaps, Perhaps, Perhaps",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/ebh7neq7c2l2afjoqzqt1/09-Perhaps-Perhaps-Perhaps.mp3?rlkey=67z3bsl3yyoy4u3p7aoo2pwke&st=v5j8s2ii&dl=0",
    play: false,
  },
  {
    name: "Everyody's Gotta Learn Sometime",
    artist: "The Korgis",
    file: "https://dl.dropboxusercontent.com/scl/fi/9yeu212ucgfwox8t7q4rs/01-Everybody-s-Got-To-Learn-Sometime.mp3?rlkey=uyvuepch4r6gg2evws8xtsvaq&st=fanctea2&dl=0",
    play: false,
  },
  {
    name: "Roads",
    artist: "Portishead",
    file: "https://dl.dropboxusercontent.com/scl/fi/ffpdxj173gya552t0plc4/1-08-Roads.mp3?rlkey=ajerwluf1rfiruumx0hj5ir9w&st=xrgm80zw&dl=0",
    play: false,
  },
  {
    name: "Unwritten",
    artist: "Natasha Bedingfield",
    file: "https://dl.dropboxusercontent.com/scl/fi/z0qjlydj4x2t3c5qaggxe/Unwritten.mp3?rlkey=0j5dpxnkq0ra0kgpgeiomyewf&st=t1tg6lft&dl=0",
    play: false,
  },
  {
    name: "You Make Me Happy",
    artist: "My Sun & Stars",
    file: "https://dl.dropboxusercontent.com/scl/fi/enh1u1me7qs7db2zjhea0/You-make-me-happy.mp3?rlkey=hz3fv5thr6k5o1q3m5n96e1ei&st=wiut35uu&dl=0",
    play: false,
  },
  {
    name: "Sour Times",
    artist: "Portishead",
    file: "https://dl.dropboxusercontent.com/scl/fi/t4u4apobecxuwdd36pcbi/1-02-Sour-Times.mp3?rlkey=ugulhicj27pf1d70fw0qhxljg&st=kwlow8xi&dl=0",
    play: false,
  },
  {
    name: "Beloved Wife",
    artist: "Natalie Merchant",
    file: "https://dl.dropboxusercontent.com/scl/fi/wr7si14dc08ehur8hj0qw/03-Natalie-Merchant-Beloved-Wife.mp3?rlkey=g2isx2n4n8ii1w81rhw6cu5u8&st=vkdfiazj&dl=0",
    play: false,
  },
  {
    name: "Home",
    artist: "Edward Sharpe & The Magnetic Zeros",
    file: "https://dl.dropboxusercontent.com/scl/fi/3znyn7c2q03ot47f5db4x/Home.mp3?rlkey=tkjrxkkyf98yg3jbnmbsc4pyx&st=eyjxjewu&dl=0",
    play: false,
  },
  {
    name: "Hot Gates",
    artist: "Mumford & Sons",
    file: "https://dl.dropboxusercontent.com/scl/fi/2nhruju2zg93ige8u9imf/1-12-Hot-Gates.mp3?rlkey=u9bmgf3mf1fg3t25sxgg95riw&st=5dok7308&dl=0",
    play: false,
  },

  {
    name: "One Night in Bangkok",
    artist: "Murray Head",
    file: "https://dl.dropboxusercontent.com/scl/fi/f8slc50wqfiabfyq8c5sb/One-Night-In-Bangkok.mp3?rlkey=sbjeqdoij6w8643ptrwz2mcib&st=uiywotlt&dl=0",
    play: false,
  },
  {
    name: "Adventure of a Lifetime",
    artist: "Coldplay",
    file: "https://dl.dropboxusercontent.com/scl/fi/50ru7cmbza3n7ouzh4huw/05-Adventure-Of-A-Lifetime.mp3?rlkey=mt8gbmjfzcvwc1rk4ianupxvd&st=owi7tws1&dl=0",
    play: false,
  },
  {
    name: "Afterlife",
    artist: "Ingrid Michaelson",
    file: "https://dl.dropboxusercontent.com/scl/fi/m5zlflcsk9dbkedhi8avf/12-Afterlife.mp3?rlkey=7363563a23lbv887vkwgywar4&st=wrq6hn60&dl=0",
    play: false,
  },
  {
    name: "Night We Met",
    artist: "Lord Huron",
    file: "https://dl.dropboxusercontent.com/scl/fi/wlux12r7hc84iz5njh6hl/14-The-Night-We-Met.mp3?rlkey=ee63lschrzeiwh6moj53004hb&st=80l31the&dl=0",
    play: false,
  },
  {
    name: "Love is like Ghosts",
    artist: "Lord Huron",
    file: "https://dl.dropboxusercontent.com/scl/fi/v1nx88wzj9fea4v4pneid/01-Love-Like-Ghosts.mp3?rlkey=9l3rtwbqq76ipqd60je9h366i&st=h10q16t4&dl=0",
    play: false,
  },
  {
    name: "Soldier",
    artist: "Ingrid Michaelson",
    file: "https://dl.dropboxusercontent.com/scl/fi/ro6g3prfr0j6tkj6ltfbn/01-Soldier.mp3?rlkey=diiytwp7pj9njohdfnn9ukh80&st=6k2eugq4&dl=0",
    play: false,
  },
  {
    name: "Everybody",
    artist: "Ingrid Michaelson",
    file: "https://dl.dropboxusercontent.com/scl/fi/qo41v4ueyqumtdjjlldio/02-Everybody.mp3?rlkey=ov1kx1swhrpxwt6g6z5snlesd&st=guf95cx8&dl=0",
    play: false,
  },
  {
    name: "Automatic",
    artist: "The Lumineers",
    file: "https://dl.dropboxusercontent.com/scl/fi/djdgp197425lwz92h8jb8/04.-Automatic.mp3?rlkey=9yz7vw0w35ur2r2a7icx9kwhs&st=823na1tm&dl=0",
    play: false,
  },
  {
    name: "Hey",
    artist: "The Lumineers",
    file: "https://dl.dropboxusercontent.com/scl/fi/lrmbia2dfe3sf0po2w1yn/05-Ho-Hey.mp3?rlkey=jueak8zfhjl5yqb4dub9igcgx&st=573onq41&dl=0",
    play: false,
  },
  {
    name: "Woman",
    artist: "Mumford & Sons",
    file: "https://dl.dropboxusercontent.com/scl/fi/y9dg72cq6e6emodqa2c1p/1-03-Woman.mp3?rlkey=7ue1kvfpa0w3p6s7b8lcnvz0w&st=zkshtzo8&dl=0",
    play: false,
  },
  {
    name: "We saw gold",
    artist: "Tones & I",
    file: "https://dl.dropboxusercontent.com/scl/fi/m0nsuopkro244w30on1ej/I-Get-High.mp3?rlkey=giuzvlv8i1euu2qb3iix5xe6p&st=wbe5y86r&dl=0",
    play: false,
  },
  {
    name: "Bad Child",
    artist: "Tones & I",
    file: "https://dl.dropboxusercontent.com/scl/fi/57gty80uysuziwjq1wtg3/Bad-Child.mp3?rlkey=89l1r02m3q04eq5282fgenr6z&st=p4lngp62&dl=0",
    play: false,
  },
  {
    name: "Death Wish Love",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/sqt4ep4drkmb2p6n427ri/Death-Wish-Love.mp3?rlkey=y350qtwje8y4mrpublj3upl97&st=049g959w&dl=0",
    play: false,
  },
  {
    name: "I Am The Highway",
    artist: "Audioslave",
    file: "https://dl.dropboxusercontent.com/scl/fi/qd9fefsq6txiwnkw97gzw/I-Am-The-Highway.mp3?rlkey=y4kh6hssi7xnpk414i80ero9d&st=uuw8nthw&dl=0",
    play: false,
  },
  {
    name: "Pretty Slowly",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/ui9dc8r8fxpm5s6tx8ymi/Pretty-Slowly.mp3?rlkey=k1mib3p97kr51q5jhul1kifda&st=7ho939vn&dl=0",
    play: false,
  },
  {
    name: "Relax My Beloved",
    artist: "Alex Clare",
    file: "https://dl.dropboxusercontent.com/scl/fi/6pyst69xaqp9hmiiv2axz/Relax-My-Beloved.mp3?rlkey=qgkkvxorfnhdh3hhd9ktffe4w&st=o68k14qd&dl=0",
    play: false,
  },
  {
    name: "Too Close",
    artist: "Alex Clare",
    file: "https://dl.dropboxusercontent.com/scl/fi/agebvadhjk35vkf6kk0m7/Too-Close.mp3?rlkey=7j1d8jug58ak57js5ikn1k11s&st=3mrugfu8&dl=0",
    play: false,
  },
  {
    name: "Wilder Mind",
    artist: "Mumford & Sons",
    file: "https://dl.dropboxusercontent.com/scl/fi/k267tm5yrh0vigh8yg36q/Wilder-Mind.mp3?rlkey=rxvsk0ryu8l3a1vyekjiilo8z&st=hz0s1pzx&dl=0",
    play: false,
  },
  {
    name: "You and Me",
    artist: "Yelawolf",
    file: "https://dl.dropboxusercontent.com/scl/fi/str3lbg8enqezfzahzmz8/You-and-Me.mp3?rlkey=dfqwaaswjobips35chr85j8r5&st=en4xe588&dl=0",
    play: false,
  },
  {
    name: "Angel By The Wings",
    artist: "Sia",
    file: "https://dl.dropboxusercontent.com/scl/fi/o54urjpf9rfds2rjdkg22/Angel-By-The-Wings.mp3?rlkey=mup2w5wpdcp7hfx3570ec9i3f&st=wos2bjib&dl=0",
    play: false,
  },
  {
    name: "Anybody Listening",
    artist: "Scorpions",
    file: "https://dl.dropboxusercontent.com/scl/fi/td17kqv7x6zhdn5pg6lq7/Anybody-Listening_.mp3?rlkey=c1di04qsfyb9tauowpza7i2xu&st=xwqrdgrs&dl=0",
    play: false,
  },
  {
    name: "Beautiful Things",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/h3jq6f1yk5tdo5jxy6go5/Beautiful-Things.mp3?rlkey=avgln5y50ykm2m39azbvxdord&st=t0b5p0cz&dl=0",
    play: false,
  },
  {
    name: "The Craving",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/u2io5qs34uydyev225wz0/01-The-Craving-Jenna-s-version.mp3?rlkey=kqqvt6b0usswdjfsucwy0aj39&st=xyp206t4&dl=0",
    play: false,
  },
  {
    name: "Volcano",
    artist: "Damien Rice",
    file: "https://dl.dropboxusercontent.com/scl/fi/8859rfgqzp1m5gjx3g81i/02-Volcano.mp3?rlkey=aibl7xc3hxurvq4luhc1ciftt&st=y3l49ud6&dl=0",
    play: false,
  },
  {
    name: "Good Girls Go to Hell",
    artist: "Billie Eilish",
    file: "https://dl.dropboxusercontent.com/scl/fi/zip2duiyisxrew7t8xq39/1-05-all-the-good-girls-go-to-hell.mp3?rlkey=uomn7qa1p19yd3p34wr3pypi7&st=hbb3huyi&dl=0",
    play: false,
  },
  {
    name: "Jive Talkin",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/2q90cj0z32at8p4o8zpuq/01-Jive-Talkin.mp3?rlkey=0ibbe6x5t5y598pf4y1199q23&st=t15tbowg&dl=0",
    play: false,
  },
  {
    name: "Bohemian Rhapsody",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/ttbyfeuanx2j8rksrxy9f/01-Bohemian-Rhapsody.mp3?rlkey=t7kmaauf5mbxnwjxaznbmd0h3&st=kkdqx9ly&dl=0",
    play: false,
  },
  {
    name: "Another One Bites the Dust",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/foic55e1loxy25nh062ns/01-Another-One-Bites-The-Dust-2011.mp3?rlkey=8p9qufnp5aj0prir3bkvvwa4m&st=3gq4e6y2&dl=0",
    play: false,
  },
  {
    name: "Under Pressure",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/r4t8gguknfbx8864d8lb9/21-Under-Pressure-Remastered-2011-_.mp3?rlkey=ja8pvw4xhxh4950xx29bn6ory&st=y9sj09yq&dl=0",
    play: false,
  },
  {
    name: "Crazy Little Thing Called Love",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/l6s03tgfzez0lt1i4mjh5/58-Crazy-Little-Thing-Called-Love-2.mp3?rlkey=yaunlu8z0qw0ssb3psubxzl4o&st=xaz26aq5&dl=0",
    play: false,
  },
  {
    name: "Songbird",
    artist: "Fleetwood Mac",
    file: "https://dl.dropboxusercontent.com/scl/fi/dodn7txt4wob7xzy9i4q5/12-Songbird.mp3?rlkey=gayzp0waxt5s37a5u1bwefbl5&st=pq2n2r72&dl=0",
    play: false,
  },
  {
    name: "Nevermore",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/59ce2325futctmi1ou49d/08-Nevermore.mp3?rlkey=rxo4p7se7y8jlpho9hhhwfdk7&st=yl0e4dwi&dl=0",
    play: false,
  },
  {
    name: "Love So Right",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/kb06pliy5cr25qyw6ebn6/07-Love-So-Right.mp3?rlkey=wbemn1hvqc6f2dmz8k4vuaftf&st=ds8dvde6&dl=0",
    play: false,
  },
  {
    name: "You're My Best Friend",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/gxcfvhw9try8br4xqv6bu/06-You-re-My-Best-Friend.mp3?rlkey=u3gmkx79gwk7zvu9gjyzq68q0&st=y7cvoj4t&dl=0",
    play: false,
  },
  {
    name: "How Deep Is Your Love",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/pxuprvczhn0vdbvqxx40z/06-How-Deep-Is-Your-Love.mp3?rlkey=iazmyq8yxgeg117ydddud5syk&st=kgnwd90g&dl=0",
    play: false,
  },
  {
    name: "Grenade",
    artist: "Bruno Mars",
    file: "https://dl.dropboxusercontent.com/scl/fi/t14ts96y0iqtes5sbdvvd/05-Grenade.mp3?rlkey=tqa8yxqa0grr86lms4t2ime0x&st=pr2kwfdh&dl=0",
    play: false,
  },
  {
    name: "Back to Black",
    artist: "Amy Winehouse",
    file: "https://dl.dropboxusercontent.com/scl/fi/jvq7g4hrz9acdfbx5wi24/05-Back-To-Black.mp3?rlkey=fxmzbmr4e1i247teeeohem350&st=xb0c33oq&dl=0",
    play: false,
  },
  {
    name: "Don't Fear the Reaper",
    artist: "Blue Oyster Cult",
    file: "https://dl.dropboxusercontent.com/scl/fi/84i8fovygxzn8ap1kxwxf/05-Don-t-Fear-The-Reaper.mp3?rlkey=oqydi3agcck5ds10r3wxip7nd&st=z4mlh2hk&dl=0",
    play: false,
  },
  {
    name: "You Should Be Dancing",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/jahf3ain9s1p1k8w74xcu/04-You-Should-Be-Dancing.mp3?rlkey=wclowa29x8bc63nsigrbdsf3z&st=e8o4bd4e&dl=0",
    play: false,
  },
  {
    name: "More Than a Woman",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/vvc5ifd08irhw4ziy2pym/04-More-Than-A-Woman.mp3?rlkey=htuwdu9pxvfd2ppmj6uwe1tqx&st=3n3tjt0n&dl=0",
    play: false,
  },
  {
    name: "Tragedy",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/1adgg9xom3ypqwoo8e78w/03-Tragedy.mp3?rlkey=5wa4o4zwwpeoxm98vfuiyctq8&st=chpmbtqi&dl=0",
    play: false,
  },
  {
    name: "My Life",
    artist: "Billy Joel",
    file: "https://dl.dropboxusercontent.com/scl/fi/zprodrfh7ckeilj5fx8k4/03-My-life.mp3?rlkey=plbt6x9nlzbix7eysp4f7m0ic&st=dg05ykl1&dl=0",
    play: false,
  },
  {
    name: "You Stepped Into My Life",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/itxnvfa64b6x27z1cayxc/02-You-Stepped-Into-My-Life.mp3?rlkey=u4iel7asnycir22kymk1ktm0c&st=3jirnt49&dl=0",
    play: false,
  },
  {
    name: "Tell Me You Love Me",
    artist: "Demi Lovato",
    file: "https://dl.dropboxusercontent.com/scl/fi/1imcc5mqhcaxplqh2sivt/02-Tell-Me-You-Love-Me.mp3?rlkey=ockbrcc8zvxr5rd08okhxmr0q&st=h2p8mt88&dl=0",
    play: false,
  },
  {
    name: "Piano Man",
    artist: "Billy Joel",
    file: "https://dl.dropboxusercontent.com/scl/fi/ue8osc6copcadvzrcxhpd/02-Piano-Man.mp3?rlkey=bqwhjre32clop4g0jwubfb064&st=7rm34bqg&dl=0",
    play: false,
  },
  {
    name: "Night Fever",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/etbf7ap39rmcnel450ddm/02-Night-Fever.mp3?rlkey=1h4wjib7rqg2747mzx5h6rgik&st=gt57ur1a&dl=0",
    play: false,
  },
  {
    name: "Big Mistake",
    artist: "Natalie Imbruglia",
    file: "https://dl.dropboxusercontent.com/scl/fi/n513kbpwupjqcrm5jvvzo/1-03-Big-Mistake.mp3?rlkey=p9xfg0lk0p5he85hpi1p8a9qu&st=gzpn72ts&dl=0",
    play: false,
  },
  {
    name: "Superman",
    artist: "Sterophonics",
    file: "https://dl.dropboxusercontent.com/scl/fi/j078dliaqocvzgtvcsphg/2-01-Superman.mp3?rlkey=6lau99btmlqr65p3i1m3imw31&st=y49m987e&dl=0",
    play: false,
  },
  {
    name: "Forgiven",
    artist: "Alanis Morissette",
    file: "https://dl.dropboxusercontent.com/scl/fi/gadamrz7ngkc0vgu9v3lc/Forgiven.mp3?rlkey=gdvag0j5ioudwrqp5hfvz6vzt&st=34bvi94d&dl=0",
    play: false,
  },
];