//updated 6/17/2025
const songs = [
  {
    name: "Green Eyes",
    artist: "Coldplay",
    file: "https://dl.dropboxusercontent.com/scl/fi/s37yyp1nawvdkm455r1bc/07-Green-Eyes.mp3?rlkey=00ko3lbh1dmkchdgku51usxg4&st=p6mconzo&dl=0",
    play: true,
  },
  {
    name: "You are the Best Thing",
    artist: "Ray LaMontagne",
    file: "https://dl.dropboxusercontent.com/scl/fi/i5xdzeqbmgjhyhyc11r9x/01-You-Are-the-Best-Thing.mp3?rlkey=nxnegc9sbpr4un7ptagw8xnnq&st=f3ya5ih3&dl=0",
    play: true,
  },
  {
    name: "Don't Stop Believin'",
    artist: "Journey",
    file: "https://dl.dropboxusercontent.com/scl/fi/fhim6y5lmtjzii5qrh13q/05-Don-t-Stop-Believin.mp3?rlkey=sm3z8rje5ougtzrjf8ew5zb29&st=xqjvtzt7&dl=0",
    play: true,
  },
  {
    name: "Mamma Mia",
    artist: "ABBA",
    file: "https://dl.dropboxusercontent.com/scl/fi/3zjh1qtr0nvcz27qjdvc3/01-Mamma-Mia.mp3?rlkey=y8ds8ttur4auck1gxgejgc44m&st=pa8j4knz&dl=0",
    play: true,
  },
  {
    name: "I wanna know what love is",
    artist: "Foreigner",
    file: "https://dl.dropboxusercontent.com/scl/fi/hjggc3qc0pfo4jfjgcrwt/1-286-I-Want-to-Know-What-Love-Is-1.mp3?rlkey=g2fv6c0dhbr3gjlmmtomxbra8&st=hyb9foj1&dl=0",
    play: true,
  },
  {
    name: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/14o4ugl7nyq3a0persu1z/04-Goodbye-Yellow-Brick-Road.mp3?rlkey=02gyozmqwaw1dbpftds19vz04&st=d6pq86s2&dl=0",
    play: true,
  },
  {
    name: "Nikita",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/ysmqippk32bi3x8ygs4ts/05-Nikita.mp3?rlkey=dw3hc6qsgpe5bxa04hcup9hs4&st=1w4yzsve&dl=0",
    play: true,
  },
  {
    name: "I'm Still Standing",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/z364l2wca993g7mtex1nz/06-I-m-Still-Standing.mp3?rlkey=glcstbuii9ws5hdzsucauas25&st=jhymve8o&dl=0",
    play: true,
  },
  {
    name: "Dont Stop Me Now",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/5kwogfiq2s36duvzz1ucj/07-Don-t-Stop-Me-Now.mp3?rlkey=3y8illq1qg8ridtnebuz63b6y&st=alfqncgw&dl=0",
    play: true,
  },
  {
    name: "Don't Go Breaking My Heart",
    artist: "Elton John & Kiki Dee",
    file: "https://dl.dropboxusercontent.com/scl/fi/kttxj718kz76t95vgl71g/08-Don-t-Go-Breaking-My-Heart-Remas.mp3?rlkey=qitwi8hocyv83921td7cdzqyf&st=8uwbkll9&dl=0",
    play: true,
  },
  {
    name: "Shallow",
    artist: "Lady Gaga & Bradley Cooper",
    file: "https://dl.dropboxusercontent.com/scl/fi/685ai8d7fjxp6bb96vaxc/12-Shallow.mp3?rlkey=zerya1ruxfd08u6oio2tqjocu&st=9u6eu3jv&dl=0",
    play: true,
  },
  {
    name: "Music To My Eyes",
    artist: "Lady Gaga & Bradley Cooper",
    file: "https://dl.dropboxusercontent.com/scl/fi/sd80tzehqby2k6ge94p2h/14-Music-To-My-Eyes.mp3?rlkey=hnmsywz29bxm8qw10b9hxp3pz&st=0uhx5xi1&dl=0",
    play: true,
  },
  {
    name: "Always Remember Us This Way",
    artist: "Lady Gaga and Bradley Cooper",
    file: "https://dl.dropboxusercontent.com/scl/fi/v5folu118b2l2e8ea12ik/17-Always-Remember-Us-This-Way.mp3?rlkey=ftzsk8y3r565tnjh3p6770f97&st=6w2bfypi&dl=0",
    play: true,
  },
  {
    name: "We Are the Champions",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/fl063q39qp0rdi1wxlymq/17-We-Are-the-Champions.mp3?rlkey=jzecp7cormbp1gnip0x4w7rjw&st=629w6nt0&dl=0",
    play: true,
  },
  {
    name: "Hotel California",
    artist: "Eagles",
    file: "https://dl.dropboxusercontent.com/scl/fi/vpnfv8h7en7szakw2ew1x/01-Hotel-California.mp3?rlkey=9ametm3qzjq98p09ymt0gw5py&st=zc0ccr8q&dl=0",
    play: true,
  },
  {
    name: "Rocketman",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/lx5231jlxosz6mqjwdlje/01-Rocket-Man-I-Think-It-s-Going-to.mp3?rlkey=gyxy0cmn6h75ffpoax2wmwu5j&st=lqmwbojo&dl=0",
    play: true,
  },
  {
    name: "Somewhere Over the Rainbow",
    artist: "Israel Kamakawiwoole",
    file: "https://dl.dropboxusercontent.com/scl/fi/lc7lvxpna6lgd0e5vij8d/Over-the-Rainbow-BrotherIs.mp3?rlkey=w6fhadp0amlkfgklqom2oqwjc&st=p0ryij8l&dl=0",
    play: true,
  },
  {
    name: "Free to wear sunscreen",
    artist: "Baz Luhrman",
    file: "https://dl.dropboxusercontent.com/scl/fi/k5anr05xp6hqmiltvmejc/01-Everybody-s-Free-To-Wear-Sunscreen-Edit.mp3?rlkey=1r8dma9sm32jbm6qj6ao2hqhy&st=6gyim8to&dl=0",
    play: true,
  },
  {
    name: "Wonderful",
    artist: "Tones & I",
    file: "https://dl.dropboxusercontent.com/scl/fi/23qr9l36ayox3vw7jxsla/07.-Wonderful.mp3?rlkey=vfrqrxdtebr8mf33ijhuvh8gj&st=tkfaw7ep&dl=0",
    play: true,
  },
  {
    name: "I Will Survive",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/6f8sfx7o3b632k9fsinu6/07-I-Will-Survive.mp3?rlkey=47i4zhrzecz67sop8xkx0is4j&st=3v9v3s8y&dl=0",
    play: true,
  },
  {
    name: "Never Enough",
    artist: "Loren Allred",
    file: "https://dl.dropboxusercontent.com/scl/fi/354m6t1yvo7ptwunm0fn2/1-06-Never-Enough.mp3?rlkey=aexgktj1e4kqele6m51pixy7b&st=cbb6px3c&dl=0",
    play: true,
  },
  {
    name: "Sail Away",
    artist: "David Gray",
    file: "https://dl.dropboxusercontent.com/scl/fi/p9o0aotznrabhcodozr2w/09-Sail-Away.mp3?rlkey=1xiomfopplzptdmwuj3ll68pl&st=ujh7d4ur&dl=0",
    play: true,
  },
  {
    name: "Takes a lot to know a Man",
    artist: "Damien Rice",
    file: "https://dl.dropboxusercontent.com/scl/fi/f2br1lb70rzvxhafhn3hb/02-It-Takes-a-Lot-to-Know-a-Man.mp3?rlkey=nkar2lq8z19fvvjt61dsg2q9g&st=oxesl61a&dl=0",
    play: true,
  },
  {
    name: "Better Together",
    artist: "Jack Johnson",
    file: "https://dl.dropboxusercontent.com/scl/fi/1krmjt0fb3rox46fjkkjj/01-Better-Together.mp3?rlkey=vw7zth9naj4t5gfjmstc467f0&st=ywp7byzh&dl=0",
    play: true,
  },
  {
    name: "Love you Madly",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/5tcohtntpa2rh2gfizkuh/09-Love-You-Madly.mp3?rlkey=kmiu63sgy1i4jtxql6m77k564&st=vojf2ufc&dl=0",
    play: true,
  },
  {
    name: "Short Skirt, Long Jacket",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/7fakohoy18rsqvt0tdge8/04-Short-Skirt_Long-Jacket.mp3?rlkey=aaqamzt2dmrxpnsyijvquxjoa&st=p7fo25nr&dl=0",
    play: true,
  },
  {
    name: "Cat People - Putting Out Fire",
    artist: "David Bowie",
    file: "https://dl.dropboxusercontent.com/scl/fi/zqap5gxnnexch1rengisb/1-663-Cat-People-Putting-Out-Fire.mp3?rlkey=ywphbhljjil7pginrn40hmu87&st=0ob3m5ga&dl=0",
    play: true,
  },
  {
    name: "Perhaps, Perhaps, Perhaps",
    artist: "Cake",
    file: "https://dl.dropboxusercontent.com/scl/fi/ebh7neq7c2l2afjoqzqt1/09-Perhaps-Perhaps-Perhaps.mp3?rlkey=67z3bsl3yyoy4u3p7aoo2pwke&st=v5j8s2ii&dl=0",
    play: true,
  },
  {
    name: "Everyody's Gotta Learn Sometime",
    artist: "The Korgis",
    file: "https://dl.dropboxusercontent.com/scl/fi/9yeu212ucgfwox8t7q4rs/01-Everybody-s-Got-To-Learn-Sometime.mp3?rlkey=uyvuepch4r6gg2evws8xtsvaq&st=fanctea2&dl=0",
    play: true,
  },
  {
    name: "Roads",
    artist: "Portishead",
    file: "https://dl.dropboxusercontent.com/scl/fi/ffpdxj173gya552t0plc4/1-08-Roads.mp3?rlkey=ajerwluf1rfiruumx0hj5ir9w&st=xrgm80zw&dl=0",
    play: true,
  },
  {
    name: "Unwritten",
    artist: "Natasha Bedingfield",
    file: "https://dl.dropboxusercontent.com/scl/fi/z0qjlydj4x2t3c5qaggxe/Unwritten.mp3?rlkey=0j5dpxnkq0ra0kgpgeiomyewf&st=t1tg6lft&dl=0",
    play: true,
  },
  {
    name: "You Make Me Happy",
    artist: "My Sun & Stars",
    file: "https://dl.dropboxusercontent.com/scl/fi/enh1u1me7qs7db2zjhea0/You-make-me-happy.mp3?rlkey=hz3fv5thr6k5o1q3m5n96e1ei&st=wiut35uu&dl=0",
    play: true,
  },
  {
    name: "Sour Times",
    artist: "Portishead",
    file: "https://dl.dropboxusercontent.com/scl/fi/t4u4apobecxuwdd36pcbi/1-02-Sour-Times.mp3?rlkey=ugulhicj27pf1d70fw0qhxljg&st=kwlow8xi&dl=0",
    play: true,
  },

  {
    name: "Beloved Wife",
    artist: "Natalie Merchant",
    file: "https://dl.dropboxusercontent.com/scl/fi/qhoop0uy5s4tl0nez0x8m/02-Beloved-Wife.mp3?rlkey=0y5bh8yvd71kn784dxtykiq84&st=okavdhjq&dl=0",
    play: true,
  },
  {
    name: "Home",
    artist: "Edward Sharpe & The Magnetic Zeros",
    file: "https://dl.dropboxusercontent.com/scl/fi/3znyn7c2q03ot47f5db4x/Home.mp3?rlkey=tkjrxkkyf98yg3jbnmbsc4pyx&st=eyjxjewu&dl=0",
    play: true,
  },
  {
    name: "Hot Gates",
    artist: "Mumford & Sons",
    file: "https://dl.dropboxusercontent.com/scl/fi/2nhruju2zg93ige8u9imf/1-12-Hot-Gates.mp3?rlkey=u9bmgf3mf1fg3t25sxgg95riw&st=5dok7308&dl=0",
    play: true,
  },

  {
    name: "One Night in Bangkok",
    artist: "Murray Head",
    file: "https://dl.dropboxusercontent.com/scl/fi/f8slc50wqfiabfyq8c5sb/One-Night-In-Bangkok.mp3?rlkey=sbjeqdoij6w8643ptrwz2mcib&st=uiywotlt&dl=0",
    play: true,
  },
  {
    name: "Adventure of a Lifetime",
    artist: "Coldplay",
    file: "https://dl.dropboxusercontent.com/scl/fi/50ru7cmbza3n7ouzh4huw/05-Adventure-Of-A-Lifetime.mp3?rlkey=mt8gbmjfzcvwc1rk4ianupxvd&st=owi7tws1&dl=0",
    play: true,
  },
  {
    name: "Afterlife",
    artist: "Ingrid Michaelson",
    file: "https://dl.dropboxusercontent.com/scl/fi/m5zlflcsk9dbkedhi8avf/12-Afterlife.mp3?rlkey=7363563a23lbv887vkwgywar4&st=wrq6hn60&dl=0",
    play: true,
  },
  {
    name: "Night We Met",
    artist: "Lord Huron",
    file: "https://dl.dropboxusercontent.com/scl/fi/wlux12r7hc84iz5njh6hl/14-The-Night-We-Met.mp3?rlkey=ee63lschrzeiwh6moj53004hb&st=80l31the&dl=0",
    play: true,
  },
  {
    name: "Love is like Ghosts",
    artist: "Lord Huron",
    file: "https://dl.dropboxusercontent.com/scl/fi/v1nx88wzj9fea4v4pneid/01-Love-Like-Ghosts.mp3?rlkey=9l3rtwbqq76ipqd60je9h366i&st=h10q16t4&dl=0",
    play: true,
  },
  {
    name: "Soldier",
    artist: "Ingrid Michaelson",
    file: "https://dl.dropboxusercontent.com/scl/fi/ro6g3prfr0j6tkj6ltfbn/01-Soldier.mp3?rlkey=diiytwp7pj9njohdfnn9ukh80&st=6k2eugq4&dl=0",
    play: true,
  },
  {
    name: "Everybody",
    artist: "Ingrid Michaelson",
    file: "https://dl.dropboxusercontent.com/scl/fi/qo41v4ueyqumtdjjlldio/02-Everybody.mp3?rlkey=ov1kx1swhrpxwt6g6z5snlesd&st=guf95cx8&dl=0",
    play: true,
  },
  {
    name: "Automatic",
    artist: "The Lumineers",
    file: "https://dl.dropboxusercontent.com/scl/fi/djdgp197425lwz92h8jb8/04.-Automatic.mp3?rlkey=9yz7vw0w35ur2r2a7icx9kwhs&st=823na1tm&dl=0",
    play: true,
  },
  {
    name: "Hey",
    artist: "The Lumineers",
    file: "https://dl.dropboxusercontent.com/scl/fi/lrmbia2dfe3sf0po2w1yn/05-Ho-Hey.mp3?rlkey=jueak8zfhjl5yqb4dub9igcgx&st=573onq41&dl=0",
    play: true,
  },
  {
    name: "Woman",
    artist: "Mumford & Sons",
    file: "https://dl.dropboxusercontent.com/scl/fi/y9dg72cq6e6emodqa2c1p/1-03-Woman.mp3?rlkey=7ue1kvfpa0w3p6s7b8lcnvz0w&st=zkshtzo8&dl=0",
    play: true,
  },
  {
    name: "We saw gold",
    artist: "Tones & I",
    file: "https://dl.dropboxusercontent.com/scl/fi/m0nsuopkro244w30on1ej/I-Get-High.mp3?rlkey=giuzvlv8i1euu2qb3iix5xe6p&st=wbe5y86r&dl=0",
    play: true,
  },
  {
    name: "PNAU Mix",
    artist: "Elton John",
    file: "https://dl.dropboxusercontent.com/scl/fi/4p9hpo906qide0dro6r8x/03-Cold-Heart-PNAU-Remix.mp3?rlkey=hqnjviz5cq2hlkxmy1gzml67w&st=tlvwqce6&dl=0",
    play: true,
  },
  {
    name: "Bad Child",
    artist: "Tones & I",
    file: "https://dl.dropboxusercontent.com/scl/fi/57gty80uysuziwjq1wtg3/Bad-Child.mp3?rlkey=89l1r02m3q04eq5282fgenr6z&st=p4lngp62&dl=0",
    play: true,
  },
  {
    name: "Death Wish Love",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/sqt4ep4drkmb2p6n427ri/Death-Wish-Love.mp3?rlkey=y350qtwje8y4mrpublj3upl97&st=049g959w&dl=0",
    play: true,
  },
  {
    name: "I Am The Highway",
    artist: "Audioslave",
    file: "https://dl.dropboxusercontent.com/scl/fi/qd9fefsq6txiwnkw97gzw/I-Am-The-Highway.mp3?rlkey=y4kh6hssi7xnpk414i80ero9d&st=uuw8nthw&dl=0",
    play: true,
  },
  {
    name: "Pretty Slowly",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/ui9dc8r8fxpm5s6tx8ymi/Pretty-Slowly.mp3?rlkey=k1mib3p97kr51q5jhul1kifda&st=7ho939vn&dl=0",
    play: true,
  },
  {
    name: "Relax My Beloved",
    artist: "Alex Clare",
    file: "https://dl.dropboxusercontent.com/scl/fi/6pyst69xaqp9hmiiv2axz/Relax-My-Beloved.mp3?rlkey=qgkkvxorfnhdh3hhd9ktffe4w&st=o68k14qd&dl=0",
    play: true,
  },
  {
    name: "Too Close",
    artist: "Alex Clare",
    file: "https://dl.dropboxusercontent.com/scl/fi/agebvadhjk35vkf6kk0m7/Too-Close.mp3?rlkey=7j1d8jug58ak57js5ikn1k11s&st=3mrugfu8&dl=0",
    play: true,
  },
  {
    name: "Wilder Mind",
    artist: "Mumford & Sons",
    file: "https://dl.dropboxusercontent.com/scl/fi/k267tm5yrh0vigh8yg36q/Wilder-Mind.mp3?rlkey=rxvsk0ryu8l3a1vyekjiilo8z&st=hz0s1pzx&dl=0",
    play: true,
  },
  {
    name: "You and Me",
    artist: "Yelawolf",
    file: "https://dl.dropboxusercontent.com/scl/fi/str3lbg8enqezfzahzmz8/You-and-Me.mp3?rlkey=dfqwaaswjobips35chr85j8r5&st=en4xe588&dl=0",
    play: true,
  },
  {
    name: "Angel By The Wings",
    artist: "Sia",
    file: "https://dl.dropboxusercontent.com/scl/fi/o54urjpf9rfds2rjdkg22/Angel-By-The-Wings.mp3?rlkey=mup2w5wpdcp7hfx3570ec9i3f&st=wos2bjib&dl=0",
    play: true,
  },
  {
    name: "Anybody Listening",
    artist: "Scorpions",
    file: "https://dl.dropboxusercontent.com/scl/fi/td17kqv7x6zhdn5pg6lq7/Anybody-Listening_.mp3?rlkey=c1di04qsfyb9tauowpza7i2xu&st=xwqrdgrs&dl=0",
    play: true,
  },
  {
    name: "Beautiful Things",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/h3jq6f1yk5tdo5jxy6go5/Beautiful-Things.mp3?rlkey=avgln5y50ykm2m39azbvxdord&st=t0b5p0cz&dl=0",
    play: true,
  },
  {
    name: "The Craving",
    artist: "Boone",
    file: "https://dl.dropboxusercontent.com/scl/fi/u2io5qs34uydyev225wz0/01-The-Craving-Jenna-s-version.mp3?rlkey=kqqvt6b0usswdjfsucwy0aj39&st=xyp206t4&dl=0",
    play: true,
  },
  {
    name: "Volcano",
    artist: "Damien Rice",
    file: "https://dl.dropboxusercontent.com/scl/fi/8859rfgqzp1m5gjx3g81i/02-Volcano.mp3?rlkey=aibl7xc3hxurvq4luhc1ciftt&st=y3l49ud6&dl=0",
    play: true,
  },
  {
    name: "Good Girls Go to Hell",
    artist: "Billie Eilish",
    file: "https://dl.dropboxusercontent.com/scl/fi/zip2duiyisxrew7t8xq39/1-05-all-the-good-girls-go-to-hell.mp3?rlkey=uomn7qa1p19yd3p34wr3pypi7&st=hbb3huyi&dl=0",
    play: true,
  },
  {
    name: "Jive Talkin",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/2q90cj0z32at8p4o8zpuq/01-Jive-Talkin.mp3?rlkey=0ibbe6x5t5y598pf4y1199q23&st=t15tbowg&dl=0",
    play: true,
  },
  {
    name: "Bohemian Rhapsody",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/ttbyfeuanx2j8rksrxy9f/01-Bohemian-Rhapsody.mp3?rlkey=t7kmaauf5mbxnwjxaznbmd0h3&st=kkdqx9ly&dl=0",
    play: true,
  },
  {
    name: "Another One Bites the Dust",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/foic55e1loxy25nh062ns/01-Another-One-Bites-The-Dust-2011.mp3?rlkey=8p9qufnp5aj0prir3bkvvwa4m&st=3gq4e6y2&dl=0",
    play: true,
  },
  {
    name: "Under Pressure",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/r4t8gguknfbx8864d8lb9/21-Under-Pressure-Remastered-2011-_.mp3?rlkey=ja8pvw4xhxh4950xx29bn6ory&st=y9sj09yq&dl=0",
    play: true,
  },
  {
    name: "Crazy Little Thing Called Love",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/l6s03tgfzez0lt1i4mjh5/58-Crazy-Little-Thing-Called-Love-2.mp3?rlkey=yaunlu8z0qw0ssb3psubxzl4o&st=xaz26aq5&dl=0",
    play: true,
  },
  {
    name: "Songbird",
    artist: "Fleetwood Mac",
    file: "https://dl.dropboxusercontent.com/scl/fi/dodn7txt4wob7xzy9i4q5/12-Songbird.mp3?rlkey=gayzp0waxt5s37a5u1bwefbl5&st=pq2n2r72&dl=0",
    play: true,
  },
  {
    name: "Nevermore",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/59ce2325futctmi1ou49d/08-Nevermore.mp3?rlkey=rxo4p7se7y8jlpho9hhhwfdk7&st=yl0e4dwi&dl=0",
    play: true,
  },
  {
    name: "Love So Right",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/kb06pliy5cr25qyw6ebn6/07-Love-So-Right.mp3?rlkey=wbemn1hvqc6f2dmz8k4vuaftf&st=ds8dvde6&dl=0",
    play: true,
  },
  {
    name: "You're My Best Friend",
    artist: "Queen",
    file: "https://dl.dropboxusercontent.com/scl/fi/gxcfvhw9try8br4xqv6bu/06-You-re-My-Best-Friend.mp3?rlkey=u3gmkx79gwk7zvu9gjyzq68q0&st=y7cvoj4t&dl=0",
    play: true,
  },
  {
    name: "How Deep Is Your Love",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/pxuprvczhn0vdbvqxx40z/06-How-Deep-Is-Your-Love.mp3?rlkey=iazmyq8yxgeg117ydddud5syk&st=kgnwd90g&dl=0",
    play: true,
  },
  {
    name: "Grenade",
    artist: "Bruno Mars",
    file: "https://dl.dropboxusercontent.com/scl/fi/t14ts96y0iqtes5sbdvvd/05-Grenade.mp3?rlkey=tqa8yxqa0grr86lms4t2ime0x&st=pr2kwfdh&dl=0",
    play: true,
  },
  {
    name: "Back to Black",
    artist: "Amy Winehouse",
    file: "https://dl.dropboxusercontent.com/scl/fi/jvq7g4hrz9acdfbx5wi24/05-Back-To-Black.mp3?rlkey=fxmzbmr4e1i247teeeohem350&st=xb0c33oq&dl=0",
    play: true,
  },
  {
    name: "Don't Fear the Reaper",
    artist: "Blue Oyster Cult",
    file: "https://dl.dropboxusercontent.com/scl/fi/84i8fovygxzn8ap1kxwxf/05-Don-t-Fear-The-Reaper.mp3?rlkey=oqydi3agcck5ds10r3wxip7nd&st=z4mlh2hk&dl=0",
    play: true,
  },
  {
    name: "You Should Be Dancing",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/jahf3ain9s1p1k8w74xcu/04-You-Should-Be-Dancing.mp3?rlkey=wclowa29x8bc63nsigrbdsf3z&st=e8o4bd4e&dl=0",
    play: true,
  },
  {
    name: "More Than a Woman",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/vvc5ifd08irhw4ziy2pym/04-More-Than-A-Woman.mp3?rlkey=htuwdu9pxvfd2ppmj6uwe1tqx&st=3n3tjt0n&dl=0",
    play: true,
  },
  {
    name: "Tragedy",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/1adgg9xom3ypqwoo8e78w/03-Tragedy.mp3?rlkey=5wa4o4zwwpeoxm98vfuiyctq8&st=chpmbtqi&dl=0",
    play: true,
  },
  {
    name: "My Life",
    artist: "Billy Joel",
    file: "https://dl.dropboxusercontent.com/scl/fi/zprodrfh7ckeilj5fx8k4/03-My-life.mp3?rlkey=plbt6x9nlzbix7eysp4f7m0ic&st=dg05ykl1&dl=0",
    play: true,
  },
  {
    name: "You Stepped Into My Life",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/itxnvfa64b6x27z1cayxc/02-You-Stepped-Into-My-Life.mp3?rlkey=u4iel7asnycir22kymk1ktm0c&st=3jirnt49&dl=0",
    play: true,
  },
  {
    name: "Tell Me You Love Me",
    artist: "Demi Lovato",
    file: "https://dl.dropboxusercontent.com/scl/fi/1imcc5mqhcaxplqh2sivt/02-Tell-Me-You-Love-Me.mp3?rlkey=ockbrcc8zvxr5rd08okhxmr0q&st=h2p8mt88&dl=0",
    play: true,
  },
  {
    name: "Piano Man",
    artist: "Billy Joel",
    file: "https://dl.dropboxusercontent.com/scl/fi/ue8osc6copcadvzrcxhpd/02-Piano-Man.mp3?rlkey=bqwhjre32clop4g0jwubfb064&st=7rm34bqg&dl=0",
    play: true,
  },
  {
    name: "Night Fever",
    artist: "BeeGees",
    file: "https://dl.dropboxusercontent.com/scl/fi/etbf7ap39rmcnel450ddm/02-Night-Fever.mp3?rlkey=1h4wjib7rqg2747mzx5h6rgik&st=gt57ur1a&dl=0",
    play: true,
  },
  {
    name: "Big Mistake",
    artist: "Natalie Imbruglia",
    file: "https://dl.dropboxusercontent.com/scl/fi/n513kbpwupjqcrm5jvvzo/1-03-Big-Mistake.mp3?rlkey=p9xfg0lk0p5he85hpi1p8a9qu&st=gzpn72ts&dl=0",
    play: true,
  },
  {
    name: "Superman",
    artist: "Sterophonics",
    file: "https://dl.dropboxusercontent.com/scl/fi/j078dliaqocvzgtvcsphg/2-01-Superman.mp3?rlkey=6lau99btmlqr65p3i1m3imw31&st=y49m987e&dl=0",
    play: true,
  },
  {
    name: "Forgiven",
    artist: "Alanis Morissette",
    file: "https://dl.dropboxusercontent.com/scl/fi/gadamrz7ngkc0vgu9v3lc/Forgiven.mp3?rlkey=gdvag0j5ioudwrqp5hfvz6vzt&st=34bvi94d&dl=0",
    play: true,
  },

];

const savedPlayStates = JSON.parse(localStorage.getItem("songPlayStates") || "null");
if (savedPlayStates && Array.isArray(savedPlayStates)) {
  songs.forEach((song, idx) => {
    if (typeof savedPlayStates[idx] === "boolean") {
      song.play = savedPlayStates[idx];
    }
  });
}
